/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tragamonedas;

import java.awt.Image;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ARTURO
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imagen1 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        imagen3 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        credito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Tragamonedas");

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/default.png"))); // NOI18N

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/default.png"))); // NOI18N

        imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/default.png"))); // NOI18N

        btnPlay.setText("Girar");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Crédito:");

        credito.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        credito.setText("10");
        credito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(imagen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imagen3)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(credito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(credito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen1)
                    .addComponent(imagen2)
                    .addComponent(imagen3))
                .addGap(18, 18, 18)
                .addComponent(btnPlay)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int creditoJuego = 10;
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();

        String imagenes[] = {"campana", "cereza", "diamante", "herradura", "manzana", "moneda", "sandia", "siete", "trebol", "uvas"};
        String img1, img2, img3, resultado1, resultado2, resultado3;
        int random1, random2, random3;

        random1 = rand.nextInt(10);
        random2 = rand.nextInt(10);
        random3 = rand.nextInt(10);
        
        resultado1 = imagenes[random1];
        resultado2 = imagenes[random2];
        resultado3 = imagenes[random3];

        img1 = "/imagenes/" + resultado1 + ".png";
        img2 = "/imagenes/" + resultado2 + ".png";
        img3 = "/imagenes/" + resultado3 + ".png";
        
        ImageIcon imgIcon1 = new ImageIcon(getClass().getResource(img1));
        Image imgEscalada1 = imgIcon1.getImage().getScaledInstance(imagen1.getWidth(), imagen1.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado1 = new ImageIcon(imgEscalada1);
        imagen1.setIcon(iconoEscalado1);

        ImageIcon imgIcon2 = new ImageIcon(getClass().getResource(img2));
        Image imgEscalada2 = imgIcon2.getImage().getScaledInstance(imagen2.getWidth(), imagen2.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado2 = new ImageIcon(imgEscalada2);
        imagen2.setIcon(iconoEscalado2);

        ImageIcon imgIcon3 = new ImageIcon(getClass().getResource(img3));
        Image imgEscalada3 = imgIcon3.getImage().getScaledInstance(imagen3.getWidth(), imagen3.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado3 = new ImageIcon(imgEscalada3);
        imagen3.setIcon(iconoEscalado3);

        creditoJuego -= 2;
        //resultado1 = resultado2 = resultado3 = "siete"; // Esta linea es para comprobar que sucede cuando sale el premio mayor
        if (resultado1.equals(resultado2) && resultado1.equals(resultado3)) {
            switch (resultado1) {
                case "siete":
                    creditoJuego += 100;
                    JOptionPane.showMessageDialog(null, "Felicidades, usted se acaba de ganar el premio mayor! \nHa sacado: siete \nSu credito aumenta a: " + creditoJuego);
                    break;
                case "campana":
                    creditoJuego += 90;
                    break;
                case "cereza":
                    creditoJuego += 80;
                    break;
                case "diamante":
                    creditoJuego += 70;
                    break;
                case "herradura":
                    creditoJuego += 60;
                    break;
                case "manzana":
                    creditoJuego += 50;
                    break;
                case "moneda":
                    creditoJuego += 40;
                    break;
                case "sandia":
                    creditoJuego += 30;
                    break;
                case "trebol":
                    creditoJuego += 20;
                    break;
                default:
                    creditoJuego += 10;
                    break;
            }
            if (!resultado1.equals("siete")) {
                JOptionPane.showMessageDialog(null, "Felicidades, usted ha sacado: " + resultado1 + "\nSu credito aumenta a: " + creditoJuego);
            }
        } else if (resultado1.equals(resultado2) || resultado1.equals(resultado3) || resultado2.equals(resultado3)) {
            creditoJuego += 2;
            JOptionPane.showMessageDialog(null, "Felicidades, usted ha sacado par" + "\nTiene un tiro libre");
        }

        this.credito.setText(String.valueOf(creditoJuego));

        if (creditoJuego == 0) {
            int depositarCredito = JOptionPane.showConfirmDialog(null, "Su saldo se agoto :( \n¿Desea depositar 10 de crédito?: ");
            if (depositarCredito == 0) {
                creditoJuego = 10;
                this.credito.setText(String.valueOf(creditoJuego));
            } else {
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Muchas gracias por usar este simulador \nAuthor: Arturo Salas Hernández");
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel credito;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
